### ISSUE TITLE
Deploying into Remote Machine 

### ISSUE THREAD

**Issue by vincentwhales** [googledrive/PyDrive#115]
This is my use case: 

I have a web portal where my clients can upload instruction files to my gdrive folder. The only OAuth token needed is mine - my web server will upload everything via my oauth token. 

I am trying to understand how I can build my own custom oauth flow given that I am deploying my applications on remote machines (Heroku). 

Currently, I have settings.yaml as such: 
```
client_config_backend: settings
client_config:
  client_id: hello
  client_secret: world

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install 
```

And I am running my oauth flow using the example:
```
self.gauth = GoogleAuth()
self.drive = GoogleDrive(self.gauth)
```

When I run this on my local machine, I am seeing a webpage firing up on my browser and asking me to authorize. Once I accept, my application works as expected. 

However, when I deploy this on Heroku, I am unable to visit the page fired. 

I tried using the following code: 
```
auth_url = gauth.GetAuthUrl() # Create authentication url user needs to visit
code = AskUserToVisitLinkAndGiveCode(auth_url) # Your customized authentication flow
gauth.Auth(code) # Authorize and build service from the code
```
The problem with this flow is that the gauth token can only be used once. And am I expected to authorize every time my webserver restarts? 

How can I replicate the flow on my webserver to the flow on my remote machines? Since `file` is the only option for `save_credentials_backend`, am I expected to manually upload the `credentials.json` to my webserver each time I deploy?
