### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by brspurri** [googledrive/PyDrive#17]
Hi there,

I am having issues authenticated via PyDrive.

When I execute the fairly basic code:

```
settings_file = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'settings.yaml')
gauth = GoogleAuth(settings_file=settings_file)
gauth.CommandLineAuth()

drive = GoogleDrive(gauth)
```

and follow the output url, and grant permissions (via the web browser), I keep seeing `redirect_uri_mismatch` followed by the description _The redirect URI in the request: urn:ietf:wg:oauth:2.0:oob did not match a registered redirect URI_. 

I'm not sure what setting to change here. My `settings.yaml` file contains:

```
client_config_backend: settings
client_config:
  client_id: <CLIENT_ID>
  client_secret: <SECRET>
  redirect_uri: http://locahost:8080/

save_credentials: True
save_credentials_backend: file
save_credentials_file: drive_credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.instal
```

And the `Redirect Uri's` and `Javascript Origins` are both set to `http://localhost:8080/` in my Google API Console.

Does anyone have any ideas what is going on here?
