### ISSUE TITLE
How to get a refresh_token?

### ISSUE THREAD

**Issue by marcobarbosa** [googledrive/PyDrive#61]
Hi,

I'd like to get the `refresh_token` for the first time only so the app doesn't require subsequent authentication prompts (as this will be a script running in the background). 

It works the first time but after the token expires it gives an error:

```
 gauth.Refresh()
  File "/Library/Python/2.7/site-packages/pydrive/auth.py", line 369, in Refresh
    raise RefreshError('No refresh_token found.'
pydrive.auth.RefreshError: No refresh_token found.Please set access_type of OAuth to offline.
```

This is the code handling the authentication:
```python
# Sort out the authentication...
gauth = GoogleAuth()

# Try to load saved client credentials
gauth.LoadCredentialsFile(os.path.dirname(os.path.realpath(__file__)) + os.sep + "credentials.json")

if gauth.credentials is None:
    # Authenticate if they're not there
    gauth.LocalWebserverAuth()
elif gauth.access_token_expired:
    # Refresh them if expired
    gauth.Refresh()
else:
    # Initialize the saved creds
    gauth.Authorize()
```

Then I have a `settings.yaml`:

```yaml
client_config_backend: settings
client_config:
  client_id: xxx
  client_secret: xxx

save_credentials: True
save_credentials_backend: file
save_credentials_file: <path_to_save_credentials.json>

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
```

I believe `client_secrets.json` is not required if you have `settings.yaml`, is that correct?

Any ideas why `refresh_token` is always `NULL` in the response `credentials.json`?
